[package]
name = "poseidon-bn254"
version = "0.1.0"
edition = "2021"

[dependencies]
ff = "0.13"
bn254 = { path = "../bn254", optional = true }
halo2curves_v1 = { package = "halo2curves", version = "0.1.0", optional = true }
halo2curves_v3 = { package = "halo2curves", git = "https://github.com/scroll-tech/halo2curves.git", branch = "base-0.3.3", optional = true }

[dev-dependencies]
poseidon-base = { git = "https://github.com/scroll-tech/poseidon-circuit", branch = "main" }

[features]
bn254 = ["dep:bn254"]
halo2curves_v1 = ["dep:halo2curves_v1"]
halo2curves_v3 = ["dep:halo2curves_v3"]