[package]
name = "poseidon-bn254"
version = "0.1.0"
edition = "2021"

[dependencies]
#bn = { package = "substrate-bn", git = "https://github.com/scroll-tech/bn", branch = "patch-v0.6.0" }
bn = { package = "substrate-bn", path = "../bn" }
itertools = "0.13"
sp1-lib = { git = "https://github.com/scroll-tech/sp1.git", branch = "scroll-dev-0803", optional = true }

[dev-dependencies]
ethers-core = { git = "https://github.com/scroll-tech/ethers-rs.git", branch = "v2.0.7" }
halo2curves = "0.1.0"
poseidon-base = { git = "https://github.com/scroll-tech/poseidon-circuit", branch = "main" }

[features]
zkvm-hint = ["sp1-lib"]